### ISSUE TITLE
buildDocs updated?

### ISSUE THREAD

**Issue by XiaosuTong** [delta-rho/docs-datadr#2]
Hi Ryan

I just noticed the documentation page for datadr and trelliscope has changed a little which added
a tessera header. And I noticed the build.R here is different which used 
optTemplates = list(navpills = pill1, brand = brand)
So are we having a new version of buildDocs package? I did not see any update in buildDocs repo.

Thank you

Xiaosu

**Comment by hafen** [comment]
Oh yeah sorry I meant to let you know about that.  Update buildDocs now - I just pushed an update.

Also you will need to add some code when you call the building functions.  Here’s an example for datadr.  You will need to grab figure/icon.png from the docs-datadr repo.

library(buildDocs)
library(staticdocs)

# make sure your working directory is set to repo base directory

brand <- "<a class='navbar-brand' href='http://tessera.io'>
  <img src='figures/icon.png' alt='tessera icon' width='30px' height='30px' style='margin-top: -6px;'>
  Tessera
</a>"
pill1 <- packageNavPill("https://github.com/tesseradata/datadr", docsActive = FALSE)
pill2 <- packageNavPill("https://github.com/tesseradata/datadr", docsActive = TRUE)

buildFunctionRef(
   packageLoc = “**path_to_rhipe_package**",
   outLoc = ".",
   optTemplates = list(navpills = pill1, brand = brand),
   copyrightText = "Tessera"
)

buildDocs(
   docsLoc = "docs",
   outLoc = ".",
   pageList = c("1intro.Rmd", "2data.Rmd", "3dnr.Rmd", "4mr.Rmd", "5divag.Rmd", "6backend.Rmd", "7faq.Rmd"),
   optTemplates = list(navpills = pill2, brand = brand),
   copyrightText = "Tessera",
   root.dir = "."
)
